services:
  - type: web
    name: quantum-paper-summarizer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: NLTK_DATA
        value: /opt/render/nltk_data

  - type: worker
    name: quantum-paper-worker
    env: python
    buildCommand: pip install -r requirements.txt && python -c "import nltk; nltk.download('punkt'); nltk.download('stopwords')"
    startCommand: python worker.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: NLTK_DATA
        value: /opt/render/nltk_data
